//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogReader.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlogReader.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About BlogReader.
        /// </summary>
        public static string AboutBlogReaderLabel {
            get {
                return ResourceManager.GetString("AboutBlogReaderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app was created by Antun Tkalčec during the Ekoship internship of 2022..
        /// </summary>
        public static string AboutPageText {
            get {
                return ResourceManager.GetString("AboutPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About BlogReader.
        /// </summary>
        public static string AboutPageTitle {
            get {
                return ResourceManager.GetString("AboutPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles.
        /// </summary>
        public static string ArticlesPageTitle {
            get {
                return ResourceManager.GetString("ArticlesPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEGIN.
        /// </summary>
        public static string BeginButton {
            get {
                return ResourceManager.GetString("BeginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Croatian.
        /// </summary>
        public static string CroatianFrameLabel {
            get {
                return ResourceManager.GetString("CroatianFrameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string EnglishFrameLabel {
            get {
                return ResourceManager.GetString("EnglishFrameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite articles.
        /// </summary>
        public static string FavoriteArticles {
            get {
                return ResourceManager.GetString("FavoriteArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite articles.
        /// </summary>
        public static string FavoritesPageTitle {
            get {
                return ResourceManager.GetString("FavoritesPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlogReader.
        /// </summary>
        public static string LandingPageTitle {
            get {
                return ResourceManager.GetString("LandingPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading articles....
        /// </summary>
        public static string LoadingArticles {
            get {
                return ResourceManager.GetString("LoadingArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no articles to display..
        /// </summary>
        public static string NullArticles {
            get {
                return ResourceManager.GetString("NullArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show articles saved for offline reading.
        /// </summary>
        public static string OfflineArticles {
            get {
                return ResourceManager.GetString("OfflineArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for articles....
        /// </summary>
        public static string SearchBarText {
            get {
                return ResourceManager.GetString("SearchBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat setup.
        /// </summary>
        public static string SettingsPageButton {
            get {
                return ResourceManager.GetString("SettingsPageButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all blogs from DB (testing).
        /// </summary>
        public static string SetupPageDeleteBlogs {
            get {
                return ResourceManager.GetString("SetupPageDeleteBlogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string SetupPageNext {
            get {
                return ResourceManager.GetString("SetupPageNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select some blogs you&apos;re interested in:.
        /// </summary>
        public static string SetupPageSubtitle {
            get {
                return ResourceManager.GetString("SetupPageSubtitle", resourceCulture);
            }
        }
    }
}
